### ISSUE TITLE
"Choose Terminal" field Not Scaling and Pushing Other Content Out-of-Screen

### ISSUE THREAD

**Issue by yes-its-rando** [KonektOU/estonian-shipping-methods-for-woocommerce#25] opened 2021-12-07 17:53 UTC
The widget where you can select SmartPost Terminal in a given city is not scaling in mobile view. So it also makes other items in the checkout page not scale thereby making other items also non visible. So cant actually checkout to finalize a purchase. The issue is also visibel on Desktop but is not as make-it-or-brake-it.

See the screenshot:

https://yahaperfumes.com/wp-content/uploads/2021/12/Thive-Ommi-Checkout-problem-b.jpg

**Comment by tjuris** [comment] 2021-12-07 18:03
This is something you could fix with CSS. Try giving the terminal select display:block and max-width:100%

**Comment by RistoNiinemets** [comment] 2021-12-07 18:44
Duplicate of #20

**Closed as completed by RistoNiinemets** 2021-12-07 18:44 UTC
